# Numpy / Pytorch Basic

Pytorch를 사용하는 것에 아직 미숙함을 가지고 계실 분들을 위해 만들어본 자료입니다.

본 자료는 http://www.numpy.org/ 를 참고하여 만들었습니다.

# Numpy

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)

In [3]:
print (data)
print (data*5)
print (data+data)
print (data.shape)
print (data.dtype)

[[-0.17256013 -0.04127844  0.05806519]
 [ 0.78544634 -1.72464421  0.45212862]]
[[-0.86280067 -0.20639221  0.29032595]
 [ 3.92723172 -8.62322104  2.26064309]]
[[-0.34512027 -0.08255688  0.11613038]
 [ 1.57089269 -3.44928842  0.90425724]]
(2, 3)
float64


In [4]:
data = np.zeros([2, 4])
print (data)
data = np.ones([2, 4])
print (data)
data = np.eye(4)
print (data)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
lst1 = [1, 2]
lst2 = [3, 4]

np1 = np.array([1, 2]) # np.asarray
np2 = np.array([3, 4]) # np.asarray

print (lst1 + lst2)
print (np1 + np2)
print (np1 * np2)

print (sum(np1 + np2))
print (np1.dot(np2))
print (np.matmul(np1.reshape(1,-1), np2)[0]) # 1*2 1*2 연산안되므로 tor1을 reshape 함.

[1, 2, 3, 4]
[4 6]
[3 8]
10
11
11


In [12]:
mat1 = np.array([[2, 5, 8], [5, 3, 1]])
mat2 = np.array([[3, 2], [5, 4], [7, 8]])
print (mat1.shape) # mat.size()
print (mat2.shape)
print (np.matmul(mat1, mat2))

(2, 3)
(3, 2)
[[87 88]
 [37 30]]


In [19]:
data = np.random.randn(4,3)
print (data)
print (data[2, :])
print (data[:, 1])
print (data[2][1])

[[ 0.02690352 -0.20458393 -0.59755324]
 [-0.43033293  1.24603727  0.92036134]
 [-0.58371012 -1.1486086  -1.09535687]
 [ 0.82526694 -0.68919969  0.19709017]]
[-0.58371012 -1.1486086  -1.09535687]
[-0.20458393  1.24603727 -1.1486086  -0.68919969]
-1.1486086007845675


In [20]:
print (np.sum(data))
print (np.mean(data))
print (np.var(data))
print (np.std(data))

-1.5336861500223553
-0.1278071791685296
0.5702687211140197
0.7551613874623223


In [22]:
print (np.where(data>0))
print (np.where(data>0, True, False))
print (data[np.where(data>0, True, False)])

(array([0, 1, 1, 3, 3]), array([0, 1, 2, 0, 2]))
[[ True False False]
 [False  True  True]
 [False False False]
 [ True False  True]]
[0.02690352 1.24603727 0.92036134 0.82526694 0.19709017]


# Pytorch

In [1]:
import torch

In [2]:
data = torch.randn(2,3)
data

tensor([[ 1.3548,  0.4835, -0.7380],
        [ 0.8203,  0.2838, -0.2831]])

### Pytorch는 NumPy를 GPU의 사용을 용이하게 하는 tool이다.

In [3]:
print (data)
print (data*5)
print (data+data)
print (data.shape)
print (data.dtype)

tensor([[ 1.3548,  0.4835, -0.7380],
        [ 0.8203,  0.2838, -0.2831]])
tensor([[ 6.7740,  2.4174, -3.6902],
        [ 4.1015,  1.4192, -1.4155]])
tensor([[ 2.7096,  0.9670, -1.4761],
        [ 1.6406,  0.5677, -0.5662]])
torch.Size([2, 3])
torch.float32


- Data를 생성하는 여러 방법

In [4]:
data = torch.zeros([2,4])
print (data)
data = torch.ones([2,4])
print (data)
data = torch.eye(4)
print (data)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


- list와 차이점 및 벡터 내적

In [5]:
lst1 = [1, 2]
lst2 = [3, 4]

tor1 = torch.tensor([1, 2])
tor2 = torch.tensor([3, 4])

print (lst1 + lst2)
print (tor1 + tor2)
print (tor1 * tor2)

print (sum(tor1 + tor2))
print (tor1.dot(tor2))
print (torch.matmul(tor1.view(1,-1), tor2)[0]) # 1*2 1*2 연산안되므로 tor1을 reshape 함.


[1, 2, 3, 4]
tensor([4, 6])
tensor([3, 8])
tensor(10)
tensor(11)
tensor(11)


- 매트릭스의 곱 (Matrix Multiplication)

In [6]:
mat1 = torch.tensor([[2, 5, 8], [5, 3, 1]])
mat2 = torch.tensor([[3, 2], [5, 4], [7, 8]])
print (mat1.shape) # mat.size()
print (mat2.shape)
print (torch.matmul(mat1, mat2))

torch.Size([2, 3])
torch.Size([3, 2])
tensor([[87, 88],
        [37, 30]])


- 인덱싱 / 슬라이싱

In [7]:
data = torch.randn(4,3)
print (data)
print (data[2, :])
print (data[:, 1])
print (data[2][1])

tensor([[ 0.4364,  0.7245, -0.3274],
        [-0.9677,  0.4115, -1.0458],
        [-0.4748, -0.3486,  0.2886],
        [-0.4584, -0.2704,  0.3775]])
tensor([-0.4748, -0.3486,  0.2886])
tensor([ 0.7245,  0.4115, -0.3486, -0.2704])
tensor(-0.3486)


- 기본적인 통계 관련 함수  

In [8]:
print (torch.sum(data))
print (torch.mean(data))
print (torch.var(data))
print (torch.std(data))
print ()
print (torch.sum(data).item())
print (torch.mean(data).item())
print (torch.var(data).item())
print (torch.std(data).item())

tensor(-1.6546)
tensor(-0.1379)
tensor(0.3318)
tensor(0.5760)

-1.6545647382736206
-0.13788039982318878
0.33181309700012207
0.5760322213172913


- Pytorch 조건문

In [9]:
print (torch.where(data>0, torch.ones(data.shape), torch.zeros(data.shape)))

tensor([[1., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


- Numpy와 호환 

In [10]:
import numpy

In [11]:
a = torch.ones(5)
print (a)
b = a.numpy()
print (b)
a = torch.from_numpy(b)
print (a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


### GPU의 사용

In [12]:
print (torch.cuda.is_available())
if torch.cuda.is_available():
    print("how many : {}".format(torch.cuda.device_count()))
print (torch.cuda.device_count())

True
how many : 4
4


In [13]:
device = 'cuda:0'
x = torch.tensor([1,1]).to(device)

In [14]:
x = torch.tensor([1,1]).cuda()
print (x)
x = x.cpu()
print (x)

tensor([1, 1], device='cuda:0')
tensor([1, 1])


In [15]:
# Computational Graph
a = torch.tensor([2.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
c = a + b
d = b + 1
e = c * d
print (a)
print (b)
print (c)
print (d)
print (e)

tensor([2.], requires_grad=True)
tensor([1.], requires_grad=True)
tensor([3.], grad_fn=<AddBackward0>)
tensor([2.], grad_fn=<AddBackward0>)
tensor([6.], grad_fn=<MulBackward0>)


In [16]:
print (a.data)
print (a.grad)
print (a.grad_fn)

tensor([2.])
None
None


In [17]:
e.backward(retain_graph=True) # gradient가 계산됨.

In [18]:
print (a.grad)
print (b.grad)
print (c.grad)
print (d.grad)
print (e.grad)

tensor([2.])
tensor([5.])
None
None
None


<ipython-input-18-0e4f815e7f57>:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  print (c.grad)
<ipython-input-18-0e4f815e7f57>:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  print (d.grad)
<ipython-input-18-0e4f815e7f57>:5: UserWarning: The .grad attribute of a T

In [19]:
# Computational Graph
a = torch.tensor([2.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
c = a + b
d = b + 1
e = c * d

c.retain_grad()
d.retain_grad()
e.retain_grad()

In [20]:
e.backward(retain_graph=True)

In [21]:
print (a.grad)
print (b.grad)
print (c.grad)
print (d.grad)
print (e.grad)

tensor([2.])
tensor([5.])
tensor([2.])
tensor([3.])
tensor([1.])


In [22]:
a.grad.zero_()
b.grad.zero_()
c.grad.zero_()
d.grad.zero_()
e.grad.zero_()

print (a.grad)
print (b.grad)
print (c.grad)
print (d.grad)
print (e.grad)

tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])


In [23]:
a = a.detach()
print (a.requires_grad)

False
